[phases.setup]
nixPkgs = ["php81", "php81Packages.composer"]

[phases.install]
cmds = ["echo 'No composer install needed for this project'"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "php -S 0.0.0.0:$PORT" 